# Dizilerde Indexleme ve Seçim

In [13]:
import numpy as np

### Tek Boyutlu Dizilerde İndexleme

In [14]:
a = np.array([10, 20, 30, 40 ,50])
a

array([10, 20, 30, 40, 50])

In [15]:
print("Ilk eleman: ", a[0])
print("Son eleman: ", a[-1])

Ilk eleman:  10
Son eleman:  50


### Tek Boyutlu Dizilerde Slicing İşlemi

In [16]:
print("Ilk 3 eleman: ", a[:3])

Ilk 3 eleman:  [10 20 30]


In [17]:
print("2 adim atlayarak: ", a[::2])

2 adim atlayarak:  [10 30 50]


### İki Boyutlu Dizilerde İndexleme

In [19]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
print("0.satir 1.sutun: ", b[0, 1], type(b[0, 1]))

0.satir 1.sutun:  2 <class 'numpy.int64'>


In [25]:
print("0.satir: ", b[0])
print("2.satir: ", b[1])

0.satir:  [1 2 3]
2.satir:  [4 5 6]


In [27]:
print("0.sutun: ", b[:, 0], type(b[:, 0]), b[:, 0].shape)

0.sutun:  [1 4 7] <class 'numpy.ndarray'> (3,)


### İki Boyutlu Dizilerde Slicing

In [30]:
print("ilk 2 satir, ilk 2 sutun:\n", b[:2, :2])

ilk 2 satir, ilk 2 sutun:
 [[1 2]
 [4 5]]


In [31]:
print("Son 2 sutun:\n", b[:, -2:])

Son 2 sutun:
 [[2 3]
 [5 6]
 [8 9]]
