# Numpy Dersleri

Numpy'da tum elemanlar ayni tiptedir.
Bu sayede daha az yer kaplar ve cok daha hizli calisir.

In [125]:
import numpy as np

#### Liste veya Tuple'dan Array Oluşturma

In [126]:
# create a np array

arr1 = np.array([1, 3, 87, 44])

type(arr1)

numpy.ndarray

In [127]:
# python array type

list1 = [5, 7, 12]

type(list1)

list

In [128]:
# python array to np array 

arr2 = np.array(list1)

type(arr2)

numpy.ndarray

In [129]:
# tuple to np array

arr3 = np.array((10, 20, 30))

type(arr3)

numpy.ndarray

#### Çok Boyutlu Array Nasıl Oluşturulur?

In [130]:
# 2x3 array

arr4 = np.array([[1, 2, 3], [4, 5, 6]])
type(arr4)

numpy.ndarray

In [131]:
# Shape, array boyutu

arr4.shape

(2, 3)

#### Sıfır, Bir Değerleri ile Dolu ve Boş Array Oluşturma 

In [132]:
z = np.zeros((2, 3)) # 2x3
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [133]:
o = np.ones((3, 2)) # 3x2
o

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [134]:
e = np.empty((2, 2)) # 2x2 boş (rastgele değer gelebilir)
e

array([[4.94e-324, 1.48e-323],
       [4.30e-322, 2.17e-322]])

In [135]:
e[0][0] = 40
e

array([[4.00e+001, 1.48e-323],
       [4.30e-322, 2.17e-322]])

In [136]:
w = np.zeros(5) # Varsayılan olarak dtype = float olur yani 0.0 
w

array([0., 0., 0., 0., 0.])

In [137]:
w2 = np.zeros(5, dtype=int)
w2

array([0, 0, 0, 0, 0])

#### Sayı Aralıkları ile Array Oluşturma

In [138]:
a1 = np.arange(0, 10, 2) # 0'dan 10'a kadar 2'şer 2'şer git.
a1

array([0, 2, 4, 6, 8])

In [139]:
s1 = np.linspace(0, 1, 5) # 0 ile 1 arasında 5 sayı oluştur.
s1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### Rastgele (Random) Array Oluşturma

In [140]:
r1 = np.random.rand(2, 3) # 2x3, 0-1 arasında float array
r1

array([[0.67184781, 0.34149835, 0.85923984],
       [0.12054977, 0.01570633, 0.55956516]])

In [142]:
r2 = np.random.randint(0, 10, (2, 3)) # 2x3, 0-9 arası integer.
r2

array([[9, 8, 9],
       [8, 5, 8]], dtype=int32)

#### dtype (Veri Tipi) ile Array Oluşturma

In [144]:
arr6 = np.array([1, 2, 3], dtype=float)
print(arr6)

[1. 2. 3.]


In [145]:
arr_bool = np.array([1, 0, 1], dtype=bool)
arr_bool

array([ True, False,  True])

#### dtype Kullanmazsak Ne Olur?

In [146]:
arr7 = np.array([1, 2, 3]) # integer olur.
arr7

array([1, 2, 3])

In [147]:
arr7.shape

(3,)

In [148]:
r2.shape

(2, 3)