# Numpy Matris Oluşturma Örnekleri

Matematikte matris veya dizey, dikdörtgen bir sayılar tablosu veya daha genel bir açıklamayla, toplanabilir veya çarpılabilir soyut miktarlar tablosudur.

In [150]:
import numpy as np

Tek boyutlu array (vektor gibi)

In [151]:
a = np.array([5, 6, 8, 7]) # 1 boyutlu array
a

array([5, 6, 8, 7])

In [152]:
a.shape

(4,)

2 Boyutlu Array

In [153]:
# 1 Satır, 4 Sütun 

b = np.array([[5, 7, 3, 4]])
print(f"Array: {b}\nShape: {b.shape}")

Array: [[5 7 3 4]]
Shape: (1, 4)


**Yukarıdaki örnekte dikkat edelim, İkisinde de içerideki liste aynı ama birinde tek boyutlu diğerinde 2 boyutlu numpy array oluşuyor.**

2 Boyutlu Array

In [154]:
# 2 satır 1 sütun

c = np.array([[3], [4]])
print(f"Shape: {c.shape}\nArray:\n{c}")

Shape: (2, 1)
Array:
[[3]
 [4]]


In [155]:
# 2 boyutlu 2x2 matris

d = np.array([[1, 2], [1, 2]])

print(f"Shape: {d.shape}\nArray:\n{d}")

Shape: (2, 2)
Array:
[[1 2]
 [1 2]]


In [156]:
# 2 boyutlu 2x3 matris

e = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Shape: {e.shape}\nArray:\n{e}")

Shape: (2, 3)
Array:
[[1 2 3]
 [4 5 6]]


In [157]:
# 2 boyutlu 3x3 matris

e2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f"Shape: {e2.shape}\n{e2}\n")

Shape: (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]



Birim Matris (eye)

In [158]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Sıfır ve Birler ile Matris

In [159]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [160]:
ones = np.ones((3, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Random Matris

In [161]:
# ex3 rastgele tam sayılar matrisi

rand_m = np.random.randint(50, 100, (2, 3))

print(f"Shape: {rand_m.shape}\n{rand_m}")

Shape: (2, 3)
[[64 86 63]
 [75 85 70]]
